CREATE TABLE IF NOT EXISTS hits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app varchar(128),
  uri varchar(128),
  ip varchar(20),
  time_stamp TIMESTAMP WITH TIME ZONE,
  CONSTRAINT hit_id PRIMARY KEY (id)
  );