version: '3.1'
services:
  stats-server:
    image: stats-server
    build: stats-server/
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    image: ewm-service
    build: ewm-service/
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6432:6432"
    volumes:
      - /var/lib/postgresql/data/
