version: '3.1'
services:
  stats-server:
    image: stats-server
    build: stat/service/
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    container_name: stat-db
    image: postgres:14-alpine
    ports:
      - "5431:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    image: ewm-service
    build: server/
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432

  ewm-db:
    container_name: ewm-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
