CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(255),
  email varchar(512) UNIQUE,
  CONSTRAINT user_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned boolean,
  title varchar(512),
  CONSTRAINT compilation_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(128),
  CONSTRAINT category_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat numeric,
  lon numeric,
  CONSTRAINT location_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation varchar(512),
  category_id BIGINT,
  crated TIMESTAMP WITH TIME ZONE,
  description varchar(512),
  event_date TIMESTAMP WITH TIME ZONE,
  initiator_id BIGINT,
  location_id BIGINT,
  paid boolean,
  participant_limit INTEGER,
  publishedOn TIMESTAMP WITH TIME ZONE,
  moderation boolean,
  state varchar(16),
  title varchar(128),
  views BIGINT,
  CONSTRAINT event_id PRIMARY KEY (id),
  FOREIGN KEY (initiator_id) REFERENCES users (id),
  FOREIGN KEY (location_id) REFERENCES locations (id),
  FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created TIMESTAMP WITH TIME ZONE,
  event_id BIGINT,
  user_id BIGINT,
  status varchar(128),
  CONSTRAINT request_id PRIMARY KEY (id),
  FOREIGN KEY (event_id) REFERENCES events (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS events_compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_id BIGINT,
  compilation_id BIGINT,
  CONSTRAINT events_compilations_id PRIMARY KEY (id),
  FOREIGN KEY (event_id) REFERENCES events (id),
  FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);